### ISSUE TITLE
The local tunnel failed in the ide.

### ISSUE THREAD

**Issue by windrinking** [milochen0418/pynecone-colab-ide#13]

**Comment by milochen0418** [comment]
After releasing Pynecone-colab-IDE to the user, the conditions for pynecone app to use the local tunnel are becoming more and more stringent. 
After the tunnel cell done.
The following are the steps that can work. And we need to follow the steps in the order. 
- Step 1. Run the Pynecone App
- Step 2. Open the backend URL
- Step 3. Submit the IP for backend URL
- Step 4. Open the frontend URL
- Step 5. Submit the IP for frontend URL

These steps can ensure everything is well. 

I will improve the IDE to highlight the user to follow the steps. so that they can always watch their running result on the tunnel link.

**Comment by windrinking** [comment]
Thanks for the five steps.

**Comment by milochen0418** [comment]
> Thanks for the five steps.

Do the steps work on your side?

**Comment by windrinking** [comment]
> > Thanks for the five steps.
> 
> Do the steps work on your side?

Yes

**Comment by milochen0418** [comment]
Nice! 
Thanks for your feedback.

**Comment by milochen0418** [comment]
> > > Thanks for the five steps.
> > 
> > 
> > Do the steps work on your side?
> 
> Yes

Nice!
Thanks for your feedback.

**Comment by milochen0418** [comment]
I'm still developing
- https://github.com/milochen0418/pynecone-colab-ide/tree/pr-fix-issue-13

**Comment by milochen0418** [comment]
Sorry for the delay to update pynecone-colab-ide for making it stable. 
local-tunnel server is not easy to setup and I'm too busy in these two weeks. 
You can still use pynecone-colab-ide. But it is just unstable, and sometimes disconnected of connect failed.

That's would be nice when pynecone team releases their function `pc preview` and pynecone-colab-ide just use this command to make the tunnel.

**Comment by milochen0418** [comment]
The pynecone's official team stop to develop the `pc preview` in their branch. 
But they are renaming pinecone to reflex and have released the reflex=0.2.0. 
Right now, I have already communicated, report bugs and upgrade the examples code to support reflex==0.2.0. 

I also makes some research for ngrok on colab.  And finally, find out some way to work.
And it looks great but need to register an account to get auth_token. 

Right now, I'm preparing new version of `pynecone-colab-ide` (will rename to reflex-colab-ide)
And will release soon. the deadline will be before 7/10. 

@windrinking , Thanks for your waiting.

**Comment by milochen0418** [comment]
Use ngrok to solve this issue
- https://github.com/milochen0418/pynecone-colab-ide/pull/16
